name: Test Onlline Shop
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Get repository code
              uses: actions/checkout@v4
            
            - name: Test
              run: npm run test
    lint:

        runs-on: ubuntu-latest
            
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Install dependencies
              run: npm ci
            
            - name: Run ESLint
              run: npm run lint
